[package]
name = "yew-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
wasm-logger = "0.2"
gloo = "0.8"
core = { path = "../core" }
